### ISSUE TITLE
Kernel Source for T1SHS33.35-23-20-12

### ISSUE THREAD

**Issue by Mohali2609** [MotorolaMobilityLLC/kernel-msm#622] opened 2024-06-23 19:30 UTC
### Build ID

Build ID:
T1SHS33.35-23-20-12

### Additional

Hello,

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 pro (Hiphi) version: `T1SHS33.35-23-20-12`

Model number: `XT2201-1`
Codename: `HIPHI`
Android: 13
Version: `T1SHS33.35-23-20-12` (latest version as of writing)
Variant: `RETEU`

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

Notif: @asbraga-motorola @chenyt9 @awheeler-mmi @mbissaromoto @TinnoOSS

TAG= T1SHS33.35-23-20-12

**Comment by asbraga-motorola** [comment] 2024-06-24 12:44
Duplicate of #603 .
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SHS33.35-23-20-12

**Closed as completed by asbraga-motorola** 2024-06-24 12:44 UTC
Labels: duplicate, request
